language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    # The SDK version used to compile your project
    - android-21
    - android-24
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository